# Generated by Django 5.0.2 on 2024-02-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_user_is_doctor_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='dob',
            new_name='date_of_bird',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='limite_patient',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_end_day',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_start_day',
        ),
    ]
