# Generated by Django 5.0.2 on 2024-02-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_rename_dob_doctor_date_of_bird_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_bird',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_bird',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_start_date', models.DateField(blank=True, null=True)),
                ('doc_end_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.doctor')),
            ],
            options={
                'verbose_name_plural': 'DoctorTimeSlots',
            },
        ),
    ]
