# Generated by Django 5.0.2 on 2024-02-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_doctor_date_of_bird_alter_patient_date_of_bird_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('motif', models.TextField()),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('choise_speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.specialization')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.doctor')),
                ('doctor_time_slots', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.doctortimeslots')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.patient')),
            ],
            options={
                'verbose_name_plural': 'Appointment',
            },
        ),
    ]
