# Generated by Django 5.0.2 on 2024-02-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_prescription_prescription_medicine_prescription_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='id',
            new_name='appointment_id',
        ),
    ]
