# Generated by Django 5.0.2 on 2024-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_id_appointment_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Information',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prescription_medicine',
            name='duration',
        ),
        migrations.AddField(
            model_name='doctor',
            name='reg_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='prescription_medicine',
            name='end_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription_medicine',
            name='start_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription_test',
            name='test_info_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
