# Generated by Django 5.0.2 on 2024-02-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0012_user_is_secretary_secretary"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretary",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="secretary",
            name="patients_of_the_day",
            field=models.ManyToManyField(to="book.patient"),
        ),
        migrations.AlterField(
            model_name="secretary",
            name="hospital_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book.hospital",
            ),
        ),
        migrations.CreateModel(
            name="PatientEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.patient"
                    ),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.secretary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientExit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.patient"
                    ),
                ),
                (
                    "secretary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.secretary"
                    ),
                ),
            ],
        ),
    ]
