# Generated by Django 5.0.2 on 2024-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0013_secretary_address_secretary_patients_of_the_day_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretary",
            name="patients_of_the_day",
        ),
    ]
