# Generated by Django 5.0.2 on 2024-02-23 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0016_remove_patientexit_patient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="days",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="extra_information",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicine_description",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicine_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="test_description",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="test_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="time",
        ),
        migrations.RemoveField(
            model_name="prescription_medicine",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="prescription_test",
            name="prescription",
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescription_medecine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.prescription_medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="prescription_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.prescription_test",
            ),
        ),
    ]
