# Generated by Django 5.0.2 on 2024-02-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0017_remove_prescription_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="prescription_medecine",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="prescription_test",
        ),
        migrations.AddField(
            model_name="prescription",
            name="extra_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription_medicine",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.prescription",
            ),
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.prescription",
            ),
        ),
    ]
