# Generated by Django 5.0.2 on 2024-02-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0018_remove_prescription_prescription_medecine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription_medicine",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_medicines",
                to="book.prescription",
            ),
        ),
        migrations.AlterField(
            model_name="prescription_test",
            name="prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription_test",
                to="book.prescription",
            ),
        ),
    ]
