# Generated by Django 5.0.2 on 2024-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0019_alter_prescription_medicine_prescription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription_medicine",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="prescription_test",
            name="prescription",
        ),
        migrations.DeleteModel(
            name="Test_Information",
        ),
        migrations.AddField(
            model_name="prescription",
            name="end_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="frequency",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="instruction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicine_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="quantity",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prescription",
            name="start_day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Prescription_medicine",
        ),
        migrations.DeleteModel(
            name="Prescription_test",
        ),
    ]
