# Generated by Django 5.0.2 on 2024-02-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0020_remove_prescription_medicine_prescription_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test_Information",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="end_day",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="instruction",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medicine_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="start_day",
        ),
        migrations.CreateModel(
            name="Prescription_medicine",
            fields=[
                ("medicine_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "medicine_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=200, null=True)),
                ("start_day", models.DateField(blank=True, null=True)),
                ("end_day", models.DateField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=200, null=True)),
                ("instruction", models.TextField(blank=True, null=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_medicines",
                        to="book.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription_test",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(blank=True, max_length=200, null=True)),
                ("test_description", models.TextField(blank=True, null=True)),
                (
                    "test_info_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_test",
                        to="book.prescription",
                    ),
                ),
            ],
        ),
    ]
