# Generated by Django 5.0.2 on 2024-03-02 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0021_test_information_remove_prescription_end_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="date_of_bird",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="date_of_bird",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="secretary",
            old_name="date_of_bird",
            new_name="date_of_birth",
        ),
    ]
