# Generated by Django 5.0.2 on 2024-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0022_rename_date_of_bird_doctor_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription_medicine",
            name="dosage",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="prescription_test",
            name="test_results",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="test_information",
            name="test_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
