# Generated by Django 5.0.2 on 2024-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0023_prescription_medicine_dosage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secretary",
            name="appointment",
        ),
    ]
